import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/components/navbar/NavBar";
import { Inter } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by Nextjs 13",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
